name: Stirling PDF
version: latest-fat
slug: stirling_pdf
url: https://github.com/Stirling-Tools/Stirling-PDF
init: false
ingress: false
panel_icon: mdi:file-pdf-box
panel_admin: false
homeassistant_api: false
hassio_api: false
description: Locally hosted web application for various PDF operations.
arch:
  - amd64
startup: application
boot: auto
ports:
  8080/tcp: 2080
ports_description:
  8080/tcp: Web interface (Not required for Ingress)
webui: "[PROTO:ssl]://[HOST]:[PORT:8080]"
map:
  - addon_config:rw
  - share:rw
  - ssl
environment:
  PUID: "1000"
  PGID: "1000"
  DOCKER_ENABLE_SECURITY: "false"
  LANGS: en_GB
  DISABLE_ADDITIONAL_FEATURES: "false"
options: {}
schema: {}
image: ghcr.io/stirling-tools/stirling-pdf
